name: build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.51.2

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test Go code
        run: go test -race -coverprofile=cover.out -covermode=atomic ./...

      # - name: Upload coverage report to CodeCov
      #   uses: codecov/codecov-action@v1.0.0
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: ./cover.out
